name: Discord Activity Bot Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ssh_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /srv/DiscordActivityBot
            git fetch
            git checkout main
            git pull
            docker-compose up -d --build
